version: "3.9"
services:
  db:
    image: postgres:14.6
    container_name: pg-storage
    ports:
      - "5437:${POSTGRES_PORT}"
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file: .env

  web:
    build:
      context: .
    container_name: web-storage
    command: sh -c "cd ./src && alembic upgrade head && cd .. && uvicorn src.main:app --host 0.0.0.0 --port 8000"
    ports:
      - "${PROJECT_PORT}:8000"
    volumes:
      - ./storage:/code/storage
    env_file: .env
    depends_on:
      - db

  nginx:
    image: nginx:stable
    container_name: nginx-storage
    ports:
      - 80:80
    volumes:
      - ./storage:/code/storage
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites-available:/etc/nginx/conf.d
    command: sh -c "envsubst < /etc/nginx/conf.d/nginx.temp > /etc/nginx/conf.d/site.conf && exec nginx -g 'daemon off;'"
    env_file: .env
    depends_on:
      - web

volumes:
  postgres_data:
